services:
  pg:
    container_name: database_postgres_dwallet
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dwallet
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  api:
    container_name: api_pucmg_nodejs_atv2
    image: node:16
    ports:
      - 3001:3001
